export default [
  {
    id: 1,
    url: 'https://m.media-amazon.com/images/I/61sGSEqDy9L._AC_UL320_.jpg',
    brandName: 'Nike',
    productName: 'Sb Adversary Mens Trainers Cj0887 Sneakers Shoes',
    rating: 1,
    price: 16760,
  },
  {
    id: 2,
    url: 'https://m.media-amazon.com/images/I/71M5ZEA9fhL._AC_UL320_.jpg',
    brandName: 'Titan',
    productName: `Men's Round Dial Watch`,
    rating: 4,
    price: 5095,
  },
  {
    id: 3,
    url: 'https://rukminim1.flixcart.com/image/312/312/l5h2xe80/mobile/4/7/l/-original-imagg4y3grhaxckf.jpeg?q=70',
    brandName: 'Nothing',
    productName: 'Phone (1) (White, 256 GB)',
    rating: 4,
    price: 31499,
  },
  {
    id: 4,
    url: 'https://m.media-amazon.com/images/I/61uxKvea0OL._AC_UL320_.jpg',
    brandName: 'Adidas',
    productName: 'AL RIHLA Football - FIFA 2022 - Size 5 (White)',
    rating: 4,
    price: 2849,
  },
  {
    id: 5,
    url: 'https://m.media-amazon.com/images/I/71voU7KCA3L._AC_UY218_.jpg',
    brandName: 'LG',
    productName: '7 Kg 5 Star Touch panel Fully-Automatic Front Load Washing Machine',
    rating: 4,
    price: 30490,
  },
  {
    id: 6,
    url: 'https://m.media-amazon.com/images/I/61sGSEqDy9L._AC_UL320_.jpg',
    brandName: 'Nike',
    productName: 'Sb Adversary Mens Trainers Cj0887 Sneakers Shoes',
    rating: 1,
    price: 16760.10,
  },
  {
    id: 7,
    url: 'https://m.media-amazon.com/images/I/71M5ZEA9fhL._AC_UL320_.jpg',
    brandName: 'Titan',
    productName: `Men's Round Dial Watch`,
    rating: 4,
    price: 5095,
  },
  {
    id: 8,
    url: 'https://rukminim1.flixcart.com/image/312/312/l5h2xe80/mobile/4/7/l/-original-imagg4y3grhaxckf.jpeg?q=70',
    brandName: 'Nothing',
    productName: 'Phone (1) (White, 256 GB)',
    rating: 4,
    price: 31499,
  },
  {
    id: 8,
    url: 'https://m.media-amazon.com/images/I/61uxKvea0OL._AC_UL320_.jpg',
    brandName: 'Adidas',
    productName: 'AL RIHLA Football - FIFA 2022 - Size 5 (White)',
    rating: 4,
    price: 2849,
  },
  {
    id: 10,
    url: 'https://m.media-amazon.com/images/I/71voU7KCA3L._AC_UY218_.jpg',
    brandName: 'LG',
    productName: '7 Kg 5 Star Touch panel Fully-Automatic Front Load Washing Machine',
    rating: 4,
    price: 30490,
  },
]