export default [
  {
    id: 1,
    url: 'https://m.media-amazon.com/images/I/61sGSEqDy9L._AC_UL320_.jpg',
    brandName: 'Nike',
    productName: 'Sb Adversary Mens Trainers Cj0887 Sneakers Shoes',
    rating: 5,
    price: 16760,
  },
  {
    id: 2,
    url: 'https://m.media-amazon.com/images/I/71M5ZEA9fhL._AC_UL320_.jpg',
    brandName: 'Titan',
    productName: `Men's Round Dial Watch`,
    rating: 4,
    price: 5095,
  },
  {
    id: 3,
    url: 'https://rukminim1.flixcart.com/image/312/312/l5h2xe80/mobile/4/7/l/-original-imagg4y3grhaxckf.jpeg?q=70',
    brandName: 'Nothing',
    productName: 'Phone (1) (White, 256 GB)',
    rating: 4,
    price: 31499,
  },
  {
    id: 4,
    url: 'https://m.media-amazon.com/images/I/61uxKvea0OL._AC_UL320_.jpg',
    brandName: 'Adidas',
    productName: 'AL RIHLA Football - FIFA 2022 - Size 5 (White)',
    rating: 4,
    price: 2849,
  },
  {
    id: 5,
    url: 'https://m.media-amazon.com/images/I/71voU7KCA3L._AC_UY218_.jpg',
    brandName: 'LG',
    productName: '7 Kg 5 Star Touch panel Fully-Automatic Front Load Washing Machine',
    rating: 3,
    price: 30490,
  },
  {
    id: 6,
    url: 'https://m.media-amazon.com/images/I/61m0W3251CL._AC_AA220_.jpg',
    brandName: 'The Book of Five Rings (Pocket Library)',
    productName: 'by MIYAMOTO MUSASHI',
    rating: 4,
    price: 249,
  },
  {
    id: 7,
    url: 'https://m.media-amazon.com/images/I/81tdbrewW0L._AC_AA220_.jpg',
    brandName: 'Kafka On The Shore',
    productName: 'by Haruki Murakami',
    rating: 4,
    price: 465,
  },
  {
    id: 8,
    url: 'https://m.media-amazon.com/images/I/61CDoErGYPL._AC_UL320_.jpg',
    brandName: 'crocs',
    productName: 'Unisex-Adult Classic Clog',
    rating: 4,
    price: 2965,
  },
  {
    id: 9,
    url: 'https://m.media-amazon.com/images/I/61gGtqfZFlL._AC_UY218_.jpg',
    brandName: 'Acer Aspire 5',
    productName: 'Gaming Laptop Intel Core i5 12th gen Processor (16 GB/512 GB SSD)',
    rating: 3,
    price: 63999,
  },
  {
    id: 10,
    url: 'https://m.media-amazon.com/images/I/712j1vD+c8L._AC_UY218_.jpg',
    brandName: 'Audio-Technica',
    productName: 'Ath-M50X Wired Over Ear Headphones Without Mic (Black)',
    rating: 5,
    price: 11990,
  },
  {
    id: 11,
    url: 'https://m.media-amazon.com/images/I/61uA2UVnYWL._AC_UY218_.jpg',
    brandName: 'Apple',
    productName: '2022 iPad Air M1 Chip (10.9-inch 64GB) - Blue',
    rating: 4,
    price: 59899,
  },
  {
    id: 12,
    url: 'https://m.media-amazon.com/images/I/61ao0+KEjZL._AC_UL320_.jpg',
    brandName: 'Casio',
    productName: 'G-Shock Black Dial Digital Watch - DW-5600BB-1DR',
    rating: 5,
    price: 6795,
  },
  {
    id: 13,
    url: 'https://m.media-amazon.com/images/I/61Ni8i6-EEL._AC_UY218_.jpg',
    brandName: 'KZ',
    productName: 'ZST PRO Wired In Ear Earphones with Mic (Black)',
    rating: 4,
    price: 2459,
  },
  {
    id: 14,
    url: 'https://m.media-amazon.com/images/I/51RcxiQNx9L._AC_UL320_.jpg',
    brandName: 'Tata',
    productName: 'Tata Tea Gold | Goodness of Elaichi, Ginger & Tulsi',
    rating: 4,
    price: 444,
  },
  {
    id: 15,
    url: 'https://m.media-amazon.com/images/I/81dlPpWPVaL._SX569_.jpg',
    brandName: 'Alesis V-Mini',
    productName: '25-Key USB MIDI Keyboard Controller with 4 Backlit Sensitive Pads',
    rating: 2,
    price: 12244,
  },
]

 
